services:
  willman:
    image: ghcr.io/austincnunn/willman:latest
    container_name: willman
    restart: unless-stopped
    ports:
      - "5050:5050"
    volumes:
      - /user/appdata/willman:/app/data
    environment:
      - DATABASE_URL=sqlite:////app/data/willman.db
      - UPLOAD_FOLDER=/app/data/uploads
